### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [vincent51689453/Digital_Twins_IC382#1]
Hi,<br><br>url : https://github.com/vincent51689453/Digital_Twins_IC382/blob/0138c62857eacd63025a7123e56ada7822d6d6be/src/robot_deep_learning/src/third_party/models/research/syntaxnet/tensorflow/tensorflow/core/platform/cloud/testdata/service_account_credentials.json <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by vincent51689453** [comment]
Really thanks for your reminder 🙇🏻‍♂️🙇🏻‍♂️
